### ISSUE TITLE
Taksim source?

### ISSUE THREAD

**Issue by jwdevel** [abuzreq/ConstrainedGraphPartitioning#1]
Hello,
I'm interested in this code, and I noticed the line in the Readme:

> I intend to provide the source code of that paper soon. The presentaion of Taksim can be seen Here.

Any plans to do that, these days?
Regardless, thanks a lot, this seems very useful to me.

**Comment by abuzreq** [comment]
Hi @jwdevel ,
Your request motivated me to finally publish the source code, so thanks for asking. You can find the code here: 
https://github.com/abuzreq/Taksim

Although bear in mind that I did not work on that code for a while, also did not have the time to properly clean it up. But I hope you find it useful nevertheless.

**Comment by jwdevel** [comment]
Thanks a lot! I will check it out.
